# Generated by Django 4.0.5 on 2023-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(max_length=100)),
                ('book_name', models.TextField(max_length=100)),
                ('book_code', models.TextField(max_length=100)),
                ('auther', models.TextField(max_length=300)),
                ('semester', models.TextField(max_length=100)),
                ('eng_branch', models.TextField(max_length=100)),
            ],
        ),
    ]
