# Generated by Django 4.0.5 on 2023-04-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_usercart_delete_cartitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usercart',
        ),
    ]
