# Generated by Django 4.0.5 on 2023-04-14 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cancel_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercart',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercart',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercart',
            name='sub_total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
