# Generated by Django 4.0.5 on 2023-04-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_usercart_cancel_order_usercart_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='book_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
