# Generated by Django 4.0.5 on 2023-04-14 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0010_usercart_bundle_name_alter_usercart_book_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='bundlecart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_name', models.ManyToManyField(related_name='bundlebooks', to='apis.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundlecart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
