# Generated by Django 4.0.5 on 2023-04-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_bundlecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundlecart',
            name='bundle_name',
            field=models.ManyToManyField(related_name='bundle_name', to='apis.books'),
        ),
    ]
